language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --prefer-source -o

script:
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
